FROM osrf/ros:noetic-desktop-full

# RUN apt-get update
# RUN apt-get install git &&  apt-get install python3-pip
# RUN echo "ALL DONE"
# install ros packages
# RUN apt-get update && apt-get install -y --no-install-recommends \
#     ros-noetic-desktop-full=1.5.0-1* \
#     && rm -rf /var/lib/apt/lists/*